---
- hosts: all

  tasks:
    - name: group | Group by OS family
      group_by: key={{ ansible_os_family }}

- hosts: Debian
  sudo: yes

  tasks:
    - name: debian | Install build dependencies
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - gcc
        - make
        - python-dev
        - python-setuptools

- hosts: RedHat
  sudo: yes

  tasks:
    - name: redhat | Install build dependencies
      yum: pkg={{ item }} state=latest
      with_items:
        - gcc
        - make
        - python-devel
        - python-setuptools

- hosts: all
  sudo: yes

  tasks:
    - name: psdash | Install via setup.py
      command: python setup.py develop chdir=/vagrant
